project: ${PUBLIC_PROJECT_NAME}
branch: ${CI_COMMIT_REF_NAME}
version: ${CI_PIPELINE_ID}
image: ${DOCKER_REGISTRY}/${IMAGE}
k8s_cluster_domain: ${K8S_CLUSTER_DOMAIN}

release: ${PUBLIC_PROJECT_NAME}
publicEnable: False
replicas: 2
maxSurge: 1
maxUnavailable: 0

podLabels:
  version: prod
  app: ${PUBLIC_PROJECT_NAME}

configMapEnabled: True
configMapFile: boot.json
mountFilePath: licenses/boot.json
mountFileSubPath: boot.json

envsEnable: True
envs:
  - name: Mongo__ConnectionString
    value: "${MONGO_CONNECTION_STRING}"
  - name: Mongo__DatabaseName
    value: "${MONGO_DATABASE_NAME}"
  - name: Redis__ConnectionString
    value: "${REDIS_CONNECTION_STRING}"
  - name: Redis__Mode
    value: cluster
  - name: Redis__Database
    value: "0"
  - name: License__BootLicensePath
    value: licenses/boot.json
  - name: License__PublicKeyPath
    value: keys/dev-public.pem
  - name: Jwt__Issuer
    value: imt-private-backend
  - name: Jwt__Audience
    value: imt-private-backend-clients
  - name: Jwt__JwtSigningKey
    value: "${JWT_SIGNING_KEY}"
  - name: Security__ApiKeyPepper
    value: "${API_KEY_PEPPER}"
  - name: Recovery__BOOTSTRAP_ADMIN_TOKEN
    value: "${BOOTSTRAP_ADMIN_TOKEN}"
  - name: Recovery__RECOVERY_ADMIN_TOKEN
    value: "${RECOVERY_ADMIN_TOKEN}"
  - name: EnterpriseSdkHost__PublicEntryUrl
    value: "https://${PUBLIC_PROJECT_NAME}-sdk.${K8S_CLUSTER_DOMAIN}/"

readinessProbeEnable: True
livenessProbeEnable: True
readinessProbePath: /health/ready
livenessProbePath: /health/live

serviceEnable: True
serviceTargetPort: 5104

ingressEnable: True

resources:
  limits:
    cpu: 2
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi
